In [3]:
import pandas as pd
import numpy as np
from scipy.signal import welch

In [4]:
segment_file = "data\segments\MSEL_00172\interictal\MSEL_00172_interictal_4Hz_segment_0.parquet"

In [7]:
def get_features(segment_file):
    segment = pd.read_parquet(segment_file)
    frequency, power = welch(segment["BVP"], fs=4.0, nperseg=120/8)
    max_index = power.argmax()
    frequency_max = frequency[max_index]
    power_max = power_max = power[max_index]

    descriptive_features = segment.describe(percentiles=[0.1, 0.5, 0.9]).values[1:,:].flatten()
    correlation_features = segment.corr().values[np.triu_indices(6, 1)]

    output_features = np.concatenate([power, [frequency_max, power_max], descriptive_features, correlation_features])
    return output_features

In [10]:
get_features(segment_file).shape

(67,)

In [1]:
C:\Users\Bailey\OneDrive\Documents\Thesis\data\data

SyntaxError: unmatched ')' (<ipython-input-1-a35077a93b18>, line 1)

In [39]:
np.concatenate([segment.mean(), segment.std(), segment.min(), segment.max(), segment.sum(), segment.ku])

array([0.28186655, 0.2887174 , 0.5414189 , 0.5404683 , 0.00786234,
       0.76977146, 0.02744319, 0.02913484, 0.05498785, 0.06388031,
       0.00159541, 0.14642905], dtype=float32)

array([0.36609381, 0.43394092, 0.55203342, 0.53342992, 0.06814162,
       0.75773728, 0.13482456, 0.14241925, 0.06604028, 0.05988007,
       0.00716988, 0.1088369 , 0.17979756, 0.21075901, 0.37682411,
       0.30897355, 0.04631144, 0.43824676, 0.24153561, 0.25927742,
       0.47202562, 0.46934679, 0.05958481, 0.63126259, 0.29369868,
       0.48958205, 0.55260205, 0.53470811, 0.06834219, 0.75911388,
       0.56224283, 0.6026369 , 0.63183389, 0.61249458, 0.07605499,
       0.90166373, 0.67983538, 0.68407828, 0.83332008, 0.65462983,
       0.09980299, 0.9834137 ])

In [46]:
segment.corr()

ACC X     ACC Y     ACC Z       BVP       EDA      TEMP
ACC X  1.000000  0.317333 -0.138211 -0.046019 -0.147976  0.010685
ACC Y  0.317333  1.000000  0.008988 -0.073662 -0.077823  0.215372
ACC Z -0.138211  0.008988  1.000000  0.079162 -0.097322 -0.146957
BVP   -0.046019 -0.073662  0.079162  1.000000  0.053213 -0.090038
EDA   -0.147976 -0.077823 -0.097322  0.053213  1.000000 -0.166621
TEMP   0.010685  0.215372 -0.146957 -0.090038 -0.166621  1.000000

array([-0.84196728, -0.23812391,  0.11324553,  0.02302193,  0.13090913,
        0.25861521, -0.09590817,  0.0150098 , -0.0364157 , -0.11378931,
        0.22369536,  0.10059292, -0.12683204, -0.02151571,  0.19448408])